### ISSUE TITLE
submit lifewatch data to ENA

### ISSUE THREAD

**Issue by renzok** [MicroB3-IS/osd-analysis#10]

**Comment by mptomasino** [comment]
To whom it may concern,
I am unable to find the 18S data produced by using the lw protocols in ENA when I tried to parse the experiment in the 'PRJEB8682' page.
Are they already submitted? 
On the contrary when you think we will be able to find this data? 

Looking forward to your reply 
kind regards 
Maria Paola Tomasino


<pre>PhD Maria Paola Tomasino
Institute of Biomembranes and Bioenergetics of Bari -⁠IBBE,
CNR Bari
 </⁠pre>

**Comment by ikostadi** [comment]
Dear Maria,

the Lifewatch Italy data is not available in ENA yet, we are working on that - that is why this issue exists. Once the data is available through ENA, it will be documented in the [OSD2014 Data Guide](/MicroB3-IS/osd-analysis/wiki/Guide-to-OSD-2014-data) and this issue will be closed. I am fairly certain you will get en email notification (becasue of the coment you wrote) and I guess there will be a short announcement through the OSD mailing list.

**Comment by ikostadi** [comment]
The data is now available for download but is not yet submitted to ENA (due to lack of manpower), see [this section](https://github.com/MicroB3-IS/osd-analysis/wiki/Guide-to-OSD-2014-data#data-deposited-in-public-archives-and-available-and-web-sites) of the [2014 OSD Data Guide](https://github.com/MicroB3-IS/osd-analysis/wiki/Guide-to-OSD-2014-data).
