### ISSUE TITLE
submit australia data to ENA

### ISSUE THREAD

**Issue by renzok** [MicroB3-IS/osd-analysis#11]

**Comment by ikostadi** [comment]
The data is now available for download but is not yet submitted to ENA (due to lack of manpower), see [this section](https://github.com/MicroB3-IS/osd-analysis/wiki/Guide-to-OSD-2014-data#data-deposited-in-public-archives-and-available-and-web-sites) of the [2014 OSD Data Guide](https://github.com/MicroB3-IS/osd-analysis/wiki/Guide-to-OSD-2014-data).
