### ISSUE TITLE
why OTU number in 18S data  is very different between file osd2014_18s---ssu---otus and osd2014_18s_lgc_otu_by_sample

### ISSUE THREAD

**Issue by svicario** [MicroB3-IS/osd-analysis#14]
Why OTU number in 18S data  is very different between file osd2014_18s---ssu---otus and osd2014_18s_lgc_otu_by_sample?        
The are 72062 more OTUs in the table than in the matrix by sample. This  excess is well distributed across all samples and does not seems special in any way.  
What cause the difference and what set of OTU should be used for the paper?

**Comment by svicario** [comment]
osd2014_18s_lgc_otu_by_sample seems the result of a clustering performed across samples starting from the per sample clustering.  If this is true, it should be added in the report. 
Counting the filled cells in the by sample table I get 168805 hit while the original number of OTU are 168826. So 21 OTU are stil missing. Maybe filtered out?
It is correct?
a mapping of the clustered OTU is available?
thanks for your work

**Comment by ikostadi** [comment]
Yes, the otu-by-sample table is generated from the per-sample clustering results. I will double-check the numbers for consistency and come back to you with more details.

cheers,
ivo

**Comment by ikostadi** [comment]
Hi @svicario,

we double-checked and the otu-by-sample table numbers are correct - this is the one you should use for analysis. The differences you describe are based on the SIVAngs maps otus between samples. I will try to explain shortly. As you correctly pointed out, SILVAngs performs 'local' (i.e. per-sample) clustering using 98% identity. Afterwards, all reference sequences from all samples are clustered at 99% identity to map the OTUs across samples (i.e. create something like 'meta' OTUs if you like). Here is a summary of the relevant files:
- /exports/osd2014_18s---ssu---otus.csv  - contains all otus from all samples
- /stats/data/osd2014_18s---ssu---otu_mapping.stats - results of otu mapping between samples (99% clustering of per-sample otu references)
- /stats/data/osd2014_18s---ssu---otu_sample_map.stats - a list of all OTUs from all samples and their respective abundances in each sample. Here you can have a sample listed more than once per OTU with different abundances - this is correct and is due to a 'meta' OTU having more than one member from the same sample. Such counts are summed per sample and are also the reason why you appear to have 21 missing otus.

You can actually recreate the  /otu_table/osd2014_18s_lgc_otu_by_sample.csv by taking all 'meta' OTU ids from the otu_mapping.stats and extracting the corresponding entries from the otu_sample_map.stats, do a little transfromation and exchange the sample_id with the sample name by using /stats/data/osd2014_18s---ssu---samples.stats.

I hope this helps. Please feel free to close this issue if the answer suffices.

Best,
ivo

PS I will forward you request to add a description of the otu mapping process to the report to the SILVA Team.

**Comment by svicario** [comment]
Dear Ivo, 
thanks for the info on "meta clustering" and forward request to add on report, gotcha on "more than one member from the same sample" in meta clustering.

I got some strange stuff on "osd2014_18s---ssu---otu_mapping.stats" where some rows (567) 
seems truncated and so is not possible to read the complete list of names of clustered sequences.
I spot out looking at the number of names in Members compared to Number of OTUs, but is clear also looking at the last name available for example
Mapping Id   last Member
5308374      HWI-M02024:112:000000000-ACJ3F:1:110
5308425      HWI-M02024
Maybe some problem in downloading, will try from the office later, or some problem in the original repos.

In any case I do not need this info for my analysis, so will continue starting from the other table. 
If you have some time you could check integrity of file "osd2014_18s---ssu---otu_mapping.stats"
Sorry for annoyance

**Comment by renzok** [comment]
guys we can close, created a separate ticket for the truncated file issue
