### ISSUE TITLE
Fix ENVO IDs in contextual data file

### ISSUE THREAD

**Issue by pbuttigieg** [MicroB3-IS/osd-analysis#24]
The ENVO IDs in the [contextual data file](https://zarafa.mpi-bremen.de/owncloud/public.php?service=files&t=f0e297f451b9944b32f4b2366c74cde3&download&path=/samples/OSD2014-env_data-2015-09-01.csv) (2015-09-01) aren't valid.

The ENVO namespace has to be in there (otherwise it could map to anything in the OBO world) and the numeric part must be 7 or 8 characters long.
So "00000447" should be "ENVO:00000447"
xref to EnvironmentOntology/envo/issues/241

It would be even better (i.e. less ambiguous and machine actionable) to include the PURLs, e.g. http://purl.obolibrary.org/obo/ENVO_00000447
But correct IDs are sufficient :sunglasses:

**Comment by renzok** [comment]
This was done on purpose. What is just missing is to doucment this.

Reasons for just giving the numeric (integer) part:
1. saves space and bandwidth
2. allows to either prefix with "ENVO:" or "http://purl.obolibrary.org/obo/ENVO_" as user wants

**Comment by pbuttigieg** [comment]
Thanks for the reply. At any rate, these should not be called ENVO IDs. They aren't and this will just cause confusion.

>Reasons for just giving the numeric (integer) part:
1. saves space and bandwidth

If you really think that the saving of space and bandwith on this is more useful than having valid IDs in a source data set used by a diverse range of users, it would be better to call the fields `envo_[biome, feature, material]_id_suffix` so the user knows that they are not IDs and they should read more deeply into the documentation.

> 2. allows to either prefix with "ENVO:" or "http://purl.obolibrary.org/obo/ENVO_" as user wants

To me, this is like giving users data like:
"et", "ad", and "eat" so they can choose to prefix it with "p" or "P" when "s" or "S" may also be used.

**Comment by pbuttigieg** [comment]
**Also be aware that some ENVO environmental features are imported from external ontologies!**
so IDs like UBERON:[0-9]{7} can occur!

**Comment by renzok** [comment]
I documented this and more now at: https://github.com/MicroB3-IS/osd-analysis/wiki/OSD-2014-environmental-data-csv-documentation

Remarks to this discussion:

1. You seem to be ignorant of the goal of the CSV file
  It is to provide users with the contextual data so that they can use it for their OSD analysis. The technical expertise of the users in our consortium varies significantly. Therefore many decisions in providing this data also include usbality aspects. 

  That said: Most users will not be interested in what the correct defintion of ENVO identifier is nor that the terms stem from an ontology. They will use the actual term provided in the biome, feature, material column. The id part is for advanced users and for them it is not much work to prefix the number to either get a purl or an identifier which you just only very recently documented on my request.

2. The columns are named biome (biome_id), material (material_id) and feature (feature_id) and are defined to have terms from the envo ontology (no need to brand them, cause we are not selling or promoting products, just focussing on data)

3. all terms are from envo namespace (no ueberon or whatsover) and they are either 7 or 8 digit

4. The choices I made are also choices that everyone has to do differently depending on scope and context if faced with badly designed identifiers. I choosed to proivde the terms in order to **NOT** let hundreds of users do complicated lookups against different versions of envo. I choosed to make sure that only envo namespaced terms are there and all from one single version. And I choosed that people do not need to know that they use controlled terms from an ontology. The ones interested will read it in the documentation. And the ones interested in branding or transforming them to envo identifiers according to your defintion can still easily do it.

5. yes, some other columns could have been more compressed. And some others like osd_id are. Again choices of usablity, solutions to obstacles and inconsistencies, matter of resources available etc.

Nothing wrong here all matter of decisions which are documented now, therefore closing ticket.
