### ISSUE TITLE
make SILVAngs analysis results for LifeWatch Italy samples available

### ISSUE THREAD

**Issue by renzok** [MicroB3-IS/osd-analysis#8]

**Comment by svicario** [comment]
Any news on this point? time start to be short. My IBBE collegues are waiting issue 10, but I am waiting this issue. Could you express a time evaluation on the resolution?

**Comment by ikostadi** [comment]
The computations are almost done. What's left is to do is prepare all the exports and otu tables. We should be able to deliver that by next Wednesday (June 10th).

**Comment by svicario** [comment]
Thanks a lot for the info.
I will try to cope with the date, but it is likely that I will not include
this data in final analysis. I am out the third week of of june.
cheers
saverio

**Comment by ikostadi** [comment]
Quick update on the delivery. The processing is done, but we figured out that there is still metadata missing for more than 10 samples. We cannot name the samples properly without this information and in order to keep confusion to a minimum, we have to gather this info before we can give the data out. Unfortunately, I cannot estimate exactly how long this will take but we are working in our best ASAP mode. Sorry for the inconvenience.

**Comment by renzok** [comment]
new estimation: June 19th

**Comment by ikostadi** [comment]
Finally done, see here https://github.com/MicroB3-IS/osd-analysis/wiki/Guide-to-OSD-2014-data#analysis-of-workable-18s-rdna-datasets-sequenced-by-lifewatch-italy
